ec2_instance_name       = "ec2_example"
instance_type           = "t2.small"
environment             = "development"
description             = "Example RedHat EL 8 EC2 Instance"
ami_name                = "ami-0a0cb6c7bcb2e4c51"